logging:
  level:
    com:
      ironbucket: DEBUG
    org:
      '[springframework]': INFO
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    region: ${EUREKA_REGION:dev-region-1}

ironbucket:
  security:
    secret: ${IRON_BUCKET_SECRET_KEY:my-super-secret-key}

spring:
  application:
    name: claimspindel

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - IronBucketVerification					
          routes:
            - id: s3-dev-route
              uri: lb://brazz-nossel
              predicates:
                - Path=/**
                - Claims=role,ROLE_DATA_INGESTOR
              filters:
                - RewritePath=/storage/s3/(?<segment>.*), /storage/s3/upload/${segment}  					
          globalcors:
            add-to-simple-url-handler-mapping: true
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${IDP_PROVIDER_PROTOCOL}://${IDP_PROVIDER_HOST}/realms/${IDP_PROVIDER_REALM}/protocol/openid-connect/certs
